### ISSUE TITLE
waiting material

### ISSUE THREAD

**Issue by ohohco** [RiotGear/rg#53] opened 2015-10-23 02:20 UTC

**Comment by gregorypratt** [comment] 2015-10-23 07:07
Duplicate of this one? https://github.com/RiotGear/rg/issues/47

v2.0.0-rc1 refactoring is almost complete. Once done the material theme is next. Its going slower than expected as I've broken my collarbone!

https://twitter.com/grumpywizards/status/653611717985988609

**Comment by sylvainpolletvillard** [comment] 2015-10-23 19:29
Hope you get well soon :) Great job you've done with RiotGear in so little time.

**Comment by ohohco** [comment] 2015-10-26 01:15
Hope you get well soon :)

**Comment by gregorypratt** [comment] 2015-11-07 08:04
Closing in favour of this one https://github.com/RiotGear/rg/issues/47

**Closed by gregorypratt** 2015-11-07 08:04 UTC
Labels: duplicate, theme
